### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###도서 목록 조회 시:
GET http://localhost:8080/admin/books


###
GET http://localhost:8080/api/admin/selling-books?page=0&size=10

###
POST http://localhost:8080/api/admin/selling-books/register
Content-Type: application/json

{
  "bookTitle": "Sample Book",
  "bookIsbn13": "9781234567890",
  "sellingBookPrice": 15000,
  "sellingBookStock": 10,
  "sellingBookPackageable": true,
  "sellingBookStatus": "SELLING",
  "categories": ["Fiction", "Adventure"],
  "imageUrl": "http://example.com/image.jpg"
}


### 판매도서 등록
POST http://localhost:8080/api/admin/selling-books/selling-register
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
  "bookId": 1,
  "price": 15000,
  "packageable": true,
  "stock": 20,
  "status": "SELLING",
  "sellingBookViewCount": 0,
  "used": false
}

### ㅇㅇ
POST http://localhost:8080/api/admin/selling-books/register
Content-Type: application/json

{
  "bookTitle": "Test Book Title",
  "bookIndex": "4565",
  "bookDescription": "A description of the test book.",
  "bookPubDate": "2025-01-01",
  "bookPriceStandard": 25.99,
  "bookIsbn13": "1231212212",
  "publisher": "창비",
  "imageUrl": "http://example.com/image.jpg",
  "categories": [
    {"categoryId": 1,
      "categoryName": "국내도서"
    }
  ],
  "authors": ["John Doe"]
}



###
GET localhost:8080/api/books/update/3