# 실행할때 vm option 으로 -Dserver.port=3000 , 3001 -> 두개의 포트만 다른 프론트가 실행됩니다.
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-secret.yml
  application:
    name: bookstore-front-dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG
server:
  port: 3000
#eureka:
#  client:
#    enabled: false