server:
  port: 3001

spring:
  config:
    activate:
      on-profile: prod2
  application:
    name: bookstore-front-prod2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: INFO