server:
  port: 3000

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: front

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: INFO