server:
  port: 3000

spring:
  config:
    activate:
      on-profile: prod1
  application:
    name: bookstore-front-prod1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: INFO