# 실행할때 vm option 으로 -Dserver.port=3000 , 3001 -> 두개의 포트만 다른 프론트가 실행됩니다.
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: front

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO

server:
  port: 3000
  servlet:
    session:
      tracking-modes: cookie

oauth:
  payco:
    loginUrl: https://id.payco.com/oauth2.0/authorize?client_id=3RDjoVxezCTITgSDTsHnlnB&response_type=code&redirect_uri=http://plzbuybook.store:3000/oauth/callback&serviceProviderCode=FRIENDS&userLocale=ko_KR