server:
  port: ${SERVER_PORT:3000}
  servlet:
    session:
      tracking-modes: cookie

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: front

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    hostname: ${HOSTNAME}

logging:
  level:
    root: INFO

oauth:
  payco:
    loginUrl: https://id.payco.com/oauth2.0/authorize?client_id=3RDjoVxezCTITgSDTsHnlnB&response_type=code&redirect_uri=https://plzbuybook.store/oauth/callback&serviceProviderCode=FRIENDS&userLocale=ko_KR