
server:
  port: 3000

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: bookstore-front1-dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: DEBUG

---

server:
  port: 3000

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: bookstore-front1-prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: INFO