name: Java CI with Maven, SonarQube, and Docker

on:
  push:
    branches: [ "develop" ]
  pull_request:
    types: [ "opened", "synchronize" ]
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean -B package --file pom.xml

      - name: Run Tests
        run: mvn test -B --file pom.xml


